In [4]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [6]:
#reading the raw Dataset
dataset=pd.read_csv('../Data/raw/grade_school_math_instructions.csv')
dataset.head()

,INSTRUCTION,RESPONSE,SOURCE
0,This math problem has got me stumped: Natalia ...,Natalia sold 48/2 = 24 clips in May.\nNatalia ...,grade-school-math
1,Weng earns $12 an hour for babysitting. Yester...,Weng earns 12/60 = $0.2 per minute.\nWorking 5...,grade-school-math
2,I'm completely lost with this math problem: Be...,"In the beginning, Betty has only 100 / 2 = $50...",grade-school-math
3,Explain how to solve this math problem: Julie ...,Maila read 12 x 2 = 24 pages today.\nSo she wa...,grade-school-math
4,I need a clearer understanding of how to solve...,He writes each friend 3*2=6 pages a week\nSo h...,grade-school-math

In [7]:
#dropping the unnecessary columns
data=dataset[['INSTRUCTION','RESPONSE']]
data.head()

,INSTRUCTION,RESPONSE
0,This math problem has got me stumped: Natalia ...,Natalia sold 48/2 = 24 clips in May.\nNatalia ...
1,Weng earns $12 an hour for babysitting. Yester...,Weng earns 12/60 = $0.2 per minute.\nWorking 5...
2,I'm completely lost with this math problem: Be...,"In the beginning, Betty has only 100 / 2 = $50..."
3,Explain how to solve this math problem: Julie ...,Maila read 12 x 2 = 24 pages today.\nSo she wa...
4,I need a clearer understanding of how to solve...,He writes each friend 3*2=6 pages a week\nSo h...

In [8]:
#dropping the duplicates
data=data.drop_duplicates()
data.head()

,INSTRUCTION,RESPONSE
0,This math problem has got me stumped: Natalia ...,Natalia sold 48/2 = 24 clips in May.\nNatalia ...
1,Weng earns $12 an hour for babysitting. Yester...,Weng earns 12/60 = $0.2 per minute.\nWorking 5...
2,I'm completely lost with this math problem: Be...,"In the beginning, Betty has only 100 / 2 = $50..."
3,Explain how to solve this math problem: Julie ...,Maila read 12 x 2 = 24 pages today.\nSo she wa...
4,I need a clearer understanding of how to solve...,He writes each friend 3*2=6 pages a week\nSo h...

In [11]:
#checking for null values
count=data.isnull().sum()
print(count)

INSTRUCTION    0
RESPONSE       0
dtype: int64

In [12]:
if count.sum()>0:
    data=data.dropna()
else:
    print("There are no null values in the dataset.")

There are no null values in the dataset.

In [13]:
#saving the preprocessed data
data.to_csv('../Data/processed/preprocessed_data.csv',index=False)